languageCode        = "en-us"
theme               = "blackburn"
title               = "Steve McGrath"
author              = "Steve McGrath"
baseurl             = "http://stevemcgrath.io/"
language            = "en"
timezone            = "US/Central"
canonifyurls        = true
paginate            = 10
copyright           = "&copy; Steve McGrath 2019"
keywords            = ["docker", "python", "security", "nodejs", "javascript", "nessus", "tenable", "tenable.io", "tenable.sc"]

[indexes]
    tag = "tags"
    topic = "topics"

[params]
    subtitle        = "Ramblings of a Security Nerd"
    brand           = "SteveMcGrath"
    googleAnalytics = "UA-79231696-1"
    highlightjs     = "github"
    highlightjs_extra_languages = ["yaml", "bash", "go", "docker", "json", "markdown", "nginx"]
    dateFormat      = "02 Jan 06 15:04"

[menu]
    [[menu.main]]
        name        = "Home"
        pre         = "<i class='fa fa-home fa-fw'></i>"
        weight      = 1
        identifier  = "home"
        url         = "/"

    [[menu.main]]
        name        = "Posts"
        pre         = "<i class='fa fa-list fa-fw'></i>"
        weight      = 2
        identifier  = "post"
        url         = "/post/"

    [[menu.main]]
        name        = "About"
        pre         = "<i class='fa fa-user fa-fw'></i>"
        weight      = 3
        identifier  = "about"
        url         = "/about/"

    [[menu.main]]
        name        = "Projects"
        pre         = "<i class='fa fa-code-fork fa-fw'></i>"
        weight      = 4
        identifier  = "projects"
        url         = "/projects/"

[social]
    twitter         = "stevemcgrath"
    facebook        = "chigeek"
    linkedin        = "chigeek"
    reddit          = "stevemcgrath"
    github          = "stevemcgrath"
    bitbucket       = "stevemcgrath"
    keybase         = "stevemcgrath"

[deploy]
type = "git"
repo = "https://github.com/SteveMcGrath/stevemcgrath.io.git"
branch = "gh-pages"